site_name: Khu học mở
site_description: Tự học mọi thứ thông qua hướng dẫn, lộ trình và các nguồn tài nguyên miễn phí trên Internet
site_author: duykhanh471
repo_url: https://github.com/daihocmo/daihocmo.github.io
repo_name: Cùng xây dựng Khu học mở

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn bắt đầu': 
    - 'Thói quen & Hệ thống': 'huong-dan/he-thong.md'
    - 'Tự học cách tự học': 'huong-dan/tu-hoc.md'
    - 'Cách đọc': 'huong-dan/doc.md'
    - 'Chuẩn bị & Thực hành': 'huong-dan/prep-practice.md'
    - 'Ghi nhớ': 'huong-dan/ghi-nho.md'
    - 'Bộ não thứ hai': 'huong-dan/bo-nao-thu-hai.md'
    - 'Mở rộng': 'huong-dan/mo-rong.md'
    - 'Thoát nghiện': 'huong-dan/thoat-nghien.md'
  - 'Chương trình học':
    - 'Tổng quan': 'chuong-trinh/index.md'
    - 'Học sinh': 'chuong-trinh/hoc-sinh.md'
    - 'Đại học/Chuyên ngành': 'chuong-trinh/dai-hoc.md'
    - 'Ngoại ngữ': 'chuong-trinh/ngoai-ngu.md'
    - 'Kĩ năng': 'chuong-trinh/ki-nang-mem.md'
    - 'Sở thích': 'chuong-trinh/so-thich.md'
  - 'Tổng hợp & Đề xuất':
    - 'Kho tổng': 'tai-nguyen/tai-nguyen.md'
    - 'Kho sách': 'tai-nguyen/kho-sach.md'
  - 'Documentation':
    - 'Hướng dẫn cơ bản': 'docs/index.md'
    - 'Phân loại công việc': 'docs/phan-loai-cong-viec.md'
    - 'Danh sách công việc': 'docs/danh-sach-cong-viec.md'
  - 'Thông tin thêm':
    - 'Về dự án': 'about/index.md'
    - 'Cộng đồng': 'about/cong-dong.md' 
    - 'Lời cảm ơn': 'about/cam-on.md'

theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
  language: vi
  # custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: white
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: black

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daihocmo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ZyEn4TTyEM
  generator: false

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - open-in-new-tab

extra_css:
  - stylesheets/homepage.css